GET http://localhost:8080/employee/getAll?page=1&size=14
Accept-Language: uz

### Get By id
GET http://localhost:8080/employee/4

### Create
POST http://localhost:8080/employee/create
Content-Type: application/json

{
  "surname": "Xusanov",
  "age": 21,
  "address": "Sirdaryo",
  "name": "Xasan",
  "phone": "55555",
  "salary": "400$",
  "positionId": 4
}

### Delete By id
DELETE http://localhost:8080/employee/delete/10

### Get By Phone
GET http://localhost:8080/employee/getByPhone/55555

###
PUT http://localhost:8080/employee/update/16
Content-Type: application/json

{
  "name": "Xasan_Xusan",
  "surname": "Xasan update",
  "age": 23,
  "address": "Yunusobod",
  "phone": "+99931234354675867689",
  "position": 6,
  "salary": "600$"
}

### Download excel
GET http://localhost:8080/employee/download-excel